#!/usr/bin/env bash
#This script diplays
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

trap 'echo " I am invisible!!!"'
while true; do
	echo "to infinity and beyond"
	sleep 2
done
