#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20.

# "displays 4 and then bad luck from China for the 4th loop iteration"
# "displays 9 and then bad luck from Japan for the 9th loop iteration"
# "displays 17 and then bad luck from Italy for the 17th loop iteration"

count=0

do
	echo "$count"
	case $count in
		"4")bad luck from China ";;
		"9")bad luck from Japan";;
		"17") bad luck from Italy";;
	esac
	(( count ++))
done
